#!/usr/bin/env bash

set -e
set -u
set -o pipefail

[[ -z "$GIPHY_API_KEY" ]] && echo "The GIPHY_API_KEY was not defined." && exit 1

declare -r -i README_IMAGES_MAX_COUNT="${README_IMAGES_MAX_COUNT:-9}"
declare -r GIPHY_SEARCH_TERMS="${GIPHY_SEARCH_TERMS:-random}"

read -d '' JQ_README_TEMPLATE <<-"EOF" || true
def slightlyRandom:
    now * 1000 * 1000;

map(
    .data
)
| add
| unique_by(
    .id
)
| sort_by(
    .id
    | explode
    | map((. * slightlyRandom * 10) % 13)
    | add
)
| map(
    try
        "[![\\(
            @html "\\(
                .title
            )"
        ) via \\(
            @html "\\(
                if .source_tld | length > 0 then
                    .source_tld
                else
                    "giphy.com"
                end
            )"
        )](\\(
            @html "\\(
                .images.fixed_height_small.webp
            )"
        ))](\\(
            @html "\\(
                .url
            )"
        ))"
    catch
        empty
)
| map(
    select(
        length > 0
    )
)
| .[
    0:($MAX_RESULTS | tonumber)
]
| .[]
EOF

declare GIPHY_SEARCH_RESULT_LIMIT="50"
declare GIPHY_SEARCH_RESULT_RATING="pg"
declare GIPHY_API_RANDOM_ID="$({ hostname; date '+%s.%N'; } | md5sum | cut --delimiter ' ' --fields 1)"

echo -n > "giphy-images.separate.json"

curl \
    --get \
    --data-urlencode "api_key=${GIPHY_API_KEY}" \
    --data-urlencode "limit=${GIPHY_SEARCH_RESULT_LIMIT}" \
    --data-urlencode "rating=${GIPHY_SEARCH_RESULT_RATING}" \
    --data-urlencode "random_id=${GIPHY_API_RANDOM_ID}" \
    "api.giphy.com/v1/gifs/trending" >> "giphy-images.separate.json"

curl \
    --get \
    --data-urlencode "api_key=${GIPHY_API_KEY}" \
    --data-urlencode "q=${GIPHY_SEARCH_TERMS}" \
    --data-urlencode "limit=${GIPHY_SEARCH_RESULT_LIMIT}" \
    --data-urlencode "rating=${GIPHY_SEARCH_RESULT_RATING}" \
    --data-urlencode "random_id=${GIPHY_API_RANDOM_ID}" \
    "https://api.giphy.com/v1/gifs/search" >> "giphy-images.separate.json"

# NOTE: not removing the file, merely replacing the contents.
echo -n > README.md

{
    jq \
        --slurp \
        --join-output \
        --arg MAX_RESULTS "$README_IMAGES_MAX_COUNT" \
        "$JQ_README_TEMPLATE" \
        "giphy-images.separate.json"

    # TODO: templating.
    echo '<br />'
    echo -n '<details>'
    echo -n '<summary>'
    echo -n '<a href="https://giphy.com/trending-gifs" target="_blank">Trending</a> + '
    echo -n "<a href=\"https://giphy.com/search/${GIPHY_SEARCH_TERMS// /-}\" target=\"_blank\">\"${GIPHY_SEARCH_TERMS}\"</a>"
    echo -n '</summary>'
    echo -n '<img height="18" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFQAAAASCAYAAADFavmwAAACGElEQVRYhe2YPUrEQBTH9wg5go1oKVoL6cTOWiwWi60E9wg5QqrFrdwjKAiCIARsLXKEnEACVlv9LDJxsy9vMjPZLKwff5gmb77+v8x7EzLi8wpbe3s5h8kEJhNG//KTBnL5ccnr0xn3d6cbAwViIGm0MbA3oIUdE3NGzK3AaqChYIEpUGJX1gRrwK/FGzEfPQBHHfO19m7rAxTicQlEYuye4q/YClBjzkdlDUExFwq01ngAoK3nwMLDYxwM1AUWSAPM55g3r5joC7SkOj29gZrYQpk7NrELJZaakcMBNUakcrOByMTHVCn1DbMH0AWrmpwp8WkXLE+gEe2Uzs1zWRKKlRcHUKnr/XtuD59tQOXpbCy01i+SzxVzXUBjMVZCfdgUqIlrJzHv3k8g0JuDR2bHSxtQaWwqYmobAKhMz0yDpazdgqN4ct0HiRgRBnR2vGR+0l7YZbxrRz2A1ikdU5UQmZqJMp+XFE/abV4rVyiEAZ2fsAtAXTpS5vOSxdfUts62gcoUsqX8WlEfGGhqmQ96pHyHt9TSc1Cgspa1PohNv0SaUACEAi1Zf4EbX0qir7wfEkvPQYFqp6KgqnMR1a2ZsvkJbdbQGHFJ+cLaeaCWhZ2ymMsac0rFrn3+JqAR+reaTWOLuawx598FahaPqOpk18+RArjoMJc1Yj8I6Dv0ap5C/32nfG4MK/NSXXXW2SdcWwb61/QFdiU5InHRidgAAAAASUVORK5CYII=" />'
    echo -n '<br />'
    echo -n '<a href="https://giphy.com/" target="_blank">Powered By GIPHY</a>'
    echo -n '</details>'
} >> README.md
